language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
  include:
    - php: 5.5
      env: components=high
    - php: 5.3.3
      env: components=low

branches:
  only:
  - master
  - stable

before_script:
  - composer --dev install
  - composer self-update
  - composer validate
  - mkdir -p build/logs

script:
  - bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - bin/test-reporter --coverage-report build/logs/clover.xml --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

notifications:
  slack:
    secure:
